image: ubuntu:16.04

pipelines:
  default:
    - step:
        name: Environment
        script:
          - apt-get update -qq
          - apt-get install build-essential -y
          - apt-get install cmake -y
          - apt-get install git -y

          - git submodule update --init

          - cmake --version
          - mkdir Build
          - cd Build

          - cmake ..
        artifacts:
          - Build/**

    - step:
        name: Build
        script:
          - apt-get update -qq
          - apt-get install build-essential -y
          - apt-get install cmake -y
          - apt-get install git -y

          - git submodule update --init

          - cd Build
          - make
        artifacts:
          - Build/**

    - step:
        name: Tests
        script:
          - cd Build/bin
          - ls -la
          - ./Test
