name: SharpVector-Build-MSBuild

on: [push]

jobs:
  Source-Debug-x64:
    name: Build Source-Debug-x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore all the packages
        run: nuget restore SharpVector.sln

      - name: Build Debug x64
        run: msbuild -p:Configuration=Debug -p:Platform=x64 SharpVector.sln -target:Source


  Source-Release-x64:
    name: Build Source-Release-x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore all the packages
        run: nuget restore SharpVector.sln

      - name: Build Debug x64
        run: msbuild -p:Configuration=Release -p:Platform=x64 SharpVector.sln -target:Source


  Examples-Debug-x64:
    name: Build Examples-Debug-x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore all the packages
        run: nuget restore SharpVector.sln

      - name: Build Debug x64
        run: msbuild -p:Configuration=Debug -p:Platform=x64 SharpVector.sln -target:Examples

      - name: Cache Examples binary
        uses: actions/upload-artifact@v2
        with:
          name: Examples-Debug-x64
          path: Build/Examples/Debug-x64/Examples.exe


  Examples-Release-x64:
    name: Build Examples-Release-x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore all the packages
        run: nuget restore SharpVector.sln

      - name: Build Debug x64
        run: msbuild -p:Configuration=Release -p:Platform=x64 SharpVector.sln -target:Examples
